baseurl: https://walves69.github.io/quixada/
languageCode: pt-br
title: Hugo Bootstrap v4 Blog
theme: hugo-theme-bootstrap4-blog
paginate: 5
summaryLength: 50
publishDir: docs
permalinks:
  page: /:slug/
  posts: /:year/:month/:title/
menu:
  sidebar:
    - name: Link 1
      url: https://example.com
    - name: Link 2
      url: https://example.org
params:
  author: Wllyssys Alves
  date_format: Mon Jan 02, 2006
  description: A simple Hugo theme based on the Bootstrap v4 blog example.
  sidebar:
    about: A simple Hugo theme based on the [Bootstrap v4 blog example](http://v4-alpha.getbootstrap.com/examples/blog/).
  social:
    twitter: username
